git mv .dockerignore apps/main/
git mv .bitmap apps/main/
git mv Dockerfile apps/main/
git mv graphql.config.js apps/main/
git mv index.html apps/main/
git mv package.json apps/main/
git mv tsconfig.json apps/main/
git mv vite.config.ts apps/main/
git mv yarn.lock apps/main/
git mv src apps/main/
git mv .storybook apps/main/
git mv patches apps/main/
git mv public apps/main/
